### ISSUE TITLE
simple & detailed description of how to validate a correct installation using a mobile phone

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#10]
I think the documentation would benefit from a simple, detailed & precise description of how to validate a correct installation using a mobile phone. e.g. do x, you should see y within 5 seconds, and so on. Something targeted at someone whose job is running tests (not developing them), who is new to this and how may not have English as their first or even second language. Ideally it would be annotated with screen captures from both the PC used to configure the session and the mobile phone used to run the session.

I'm assuming it would be something like this.
-  Open the landing page on the phone http://<host_ip>:<port>/_wave/index.html & make a note of the session token
- Screen capture from phone, ideally with the session token highlighted, e.g. red oval drawn with a paint program
- Open the configuration page on a PC http://<host_ip>:<port>/_wave/configuration.html
- Screen capture from the PC
- Enter the first 8 characters of the session token & press return
- Screen capture
- On the PC choose APIs "none" 
- Screen capture
- On the PC, click on the label of "AVC" (not the check-box) and choose sequential track playback
- Leave "test types" with both manual and automatic selected
- Press "start session"
- On the phone, the landing page will change to ....
and so on.

**Comment by FritzHeiden** [comment]
@jpiesing I added a usage guide on running tests on mobile here: https://github.com/cta-wave/dpctf-deploy/blob/master/MOBILE_USAGE.md

**Comment by jpiesing** [comment]
Looks great. Thank you.
