### ISSUE TITLE
Building the dpctf container

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/dpctf-deploy#100]
Completely deleted (uninstalled) and reinstalled WSL2/Ubuntu and installed Docker engine/cli/docker-compose using linux terminal.    
Docker --version: Docker version 26.1.4, build 5650f9b
Docker compose --version: Docker Compose version v2.27.1
Docker Login successful
Update config.json: "localhost"
Update docker-compose.yml: "yes"
Run "Hello World" works fine. 
But after ./build.sh, ./import.sh (both ran fine) when I run docker-compose up I get 
WARN[0000] /mnt/c/users/brose/dpctf-deploy/docker-compose.yml: `version` is obsolete
[+] Running 1/1
 ✘ dpctf Error pull access denied for dpctf, repository does not exist or may require 'docker logi...              0.8s
Error response from daemon: pull access denied for dpctf, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

Docker image shows REPOSITORY    TAG       IMAGE ID       CREATED         SIZE
python        3.8       f67d8dfd7883   2 months ago    996MB
hello-world   latest    d2c94e258dcb   13 months ago   13.3kB
Docker ps shows no containers
docker ps -a shows 4ae532256603   hello-world   "/hello"   47 minutes ago   Exited (0) 47 minutes ago

Any help is welcome.

**Comment by gitwjr** [comment]
A call would be great but I am out of the office until monday  the 24th. Are you available any time next week?

**Comment by afrawei** [comment]
After pull new release of docker-compose.yaml, my issue is sovled. Thank you!

**Comment by louaybassbouss** [comment]
@gitwjr  the issue is also solved on your side can we close this issue?

**Comment by jpiesing** [comment]
> @gitwjr the issue is also solved on your side can we close this issue?

If the issue is solved great but which version is the fix included in? Is the fix only in the master? Does it need to be added to the version tagged 2.0.0?

**Comment by gitwjr** [comment]
The issue was resolved on my end as well.

**Comment by jpiesing** [comment]
Re-opening the issue as we need clarity about where the fix has landed. Is the fix in "master", in "v2.0.0", in both? If it's in master and not in v2.0.0 then users may not see it.

**Comment by louaybassbouss** [comment]
> Re-opening the issue as we need clarity about where the fix has landed. Is the fix in "master", in "v2.0.0", in both? If it's in master and not in v2.0.0 then users may not see it.

in both

**Comment by gitwjr** [comment]
We can close this issue. The change fixed it.
