### ISSUE TITLE
http://<host_ip>:/_wave/configuration.html "The specified session does not exist or is already expired."

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#11]
Somewhere in killing and restarting the docker image trying to chase other problems, something is broken.

 http://192.168.40.53:8000/_wave/configuration.html comes up with the error message "The specified session does not exist or is already expired. " . It was working on Friday and I've not reverted to an old version.

The docker log includes the following;

INFO:web-platform-tests:Starting https server on web-platform.test:8443
DEBUG:web-platform-tests:GET /_wave/configuration.html
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/configuration.html (None) 0
DEBUG:web-platform-tests:GET /_wave/css/bulma-0.7.5/bulma.min.css
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/css/bulma-0.7.5/bulma.min.css (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/css/fontawesome-5.7.2.min.css
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:GET /_wave/lib/utils.js
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/css/fontawesome-5.7.2.min.css (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/lib/wave-service.js
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:GET /_wave/lib/ui.js
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/lib/wave-service.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:200 GET /_wave/lib/utils.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:200 GET /_wave/lib/ui.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /favicon.ico
DEBUG:web-platform-tests:Found handler FileHandler
DEBUG:web-platform-tests:404 GET /favicon.ico (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/res/wavelogo_2016.jpg
DEBUG:web-platform-tests:GET /_wave/api/tests/apis
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/api/tests/apis (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:200 GET /_wave/res/wavelogo_2016.jpg (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/api/sessions/public
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/api/sessions/public (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/api/sessions/undefined/status
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:404 GET /_wave/api/sessions/undefined/status (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/configuration.html
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/configuration.html (None) 0
DEBUG:web-platform-tests:GET /_wave/lib/utils.js
DEBUG:web-platform-tests:GET /_wave/lib/ui.js
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/lib/ui.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/lib/wave-service.js
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/lib/wave-service.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:200 GET /_wave/lib/utils.js (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/css/bulma-0.7.5/bulma.min.css
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/css/bulma-0.7.5/bulma.min.css (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/css/fontawesome-5.7.2.min.css
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/css/fontawesome-5.7.2.min.css (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/res/wavelogo_2016.jpg
DEBUG:web-platform-tests:GET /_wave/api/tests/apis
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/res/wavelogo_2016.jpg (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:200 GET /_wave/api/tests/apis (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/api/sessions/public
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:200 GET /_wave/api/sessions/public (http://192.168.40.53:8000/_wave/configuration.html) 0
DEBUG:web-platform-tests:GET /_wave/api/sessions/undefined/status
DEBUG:web-platform-tests:Found handler WaveHandler
DEBUG:web-platform-tests:404 GET /_wave/api/sessions/undefined/status (http://192.168.40.53:8000/_wave/configuration.html) 0

**Comment by jpiesing** [comment]
I've just run a session on a phone & a second session on the laptop that's hosting the docker instance. Both of them successful. Both of them have a results page. Directories have appeared in /results/ for both sessions but configuration.html still shows the above error message.

**Comment by louaybassbouss** [comment]
@jpiesing  if you go with the version from last week to `http://<host_ip>:<port>/_wave/configuration.html`, it is expected that you see the message "The specified session does not exist or is already expired", because there is no token provided as query parameter. In the lastest version (the one you tested), you should see a field where you can enter the token instead.

**Comment by jpiesing** [comment]
@louaybassbouss Theres no field where I can enter the token. There was on Friday.
![image](https://user-images.githubusercontent.com/8490792/116082629-ea8a3580-a69b-11eb-865a-4d21375303bb.png)

**Comment by louaybassbouss** [comment]
> @louaybassbouss Today there is no field where I can enter the token. There was such a field on Friday.
> ![image](https://user-images.githubusercontent.com/8490792/116082629-ea8a3580-a69b-11eb-865a-4d21375303bb.png)

@jpiesing we didn't make any change to the dpctf-* projects since the update last week. It should be something with your docker. In worst case please remove the old docker images and containers and create them again.

**Comment by jpiesing** [comment]
@louaybassbouss @FritzHeiden Still broken after this ...

docker stop dpctf ; git pull ; ./build.sh master latest 1 1 ; docker-compose up -d ; docker start dpctf

**Comment by louaybassbouss** [comment]
@jpiesing you can use [docker container ls -a](https://docs.docker.com/engine/reference/commandline/container_ls/) and [docker image ls -a](https://docs.docker.com/engine/reference/commandline/image_ls/) to list containers/images and [docker container rm](https://docs.docker.com/engine/reference/commandline/container_rm/) [docker image rm](https://docs.docker.com/engine/reference/commandline/image_rm/) to remove.

**Comment by jpiesing** [comment]
> @jpiesing you can use [docker container ls -a](https://docs.docker.com/engine/reference/commandline/container_ls/) and [docker image ls -a](https://docs.docker.com/engine/reference/commandline/image_ls/) to list containers/images and [docker container rm](https://docs.docker.com/engine/reference/commandline/container_rm/) [docker image rm](https://docs.docker.com/engine/reference/commandline/image_rm/) to remove.
It now works.
