### ISSUE TITLE
Link to the latest release

### ISSUE THREAD

**Issue by louaybassbouss** [cta-wave/dpctf-deploy#114]
The [WAVE Test Suite Landing Page](https://www.cta.tech/Resources/Standards/WAVE-Project/WAVE-Streaming-Media-Test-Suite-Devices) includes a link to the [dpctf-deploy GH repo](https://github.com/cta-wave/dpctf-deploy) (currently it points to [v2.0.0](https://github.com/cta-wave/dpctf-deploy/tree/v2.0.0)). Everytime we release a new version, the URL on the landing page needs to be updated. For example, currently version [v2.0.1](https://github.com/cta-wave/dpctf-deploy/tree/v2.0.1) is released. 

We need a mechanism to point to the latest release without the need to always change the URL on the landing page. 

Ideas: 
- master branch is always identical with the last release. Everything else happens in staging branch. This way we can safely use https://github.com/cta-wave/dpctf-deploy  as a pointer to the last release.

**Comment by gitwjr** [comment]
Fixed. Close.
