### ISSUE TITLE
wrong media stream being installed for sequential track playback

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#12]
I'm seeing lots of dropped frames - >950 on Android and >100 on a PC.
I assume this is https://github.com/cta-wave/dpctf-tests/issues/18 and that the wrong stream has been installed.

**Comment by louaybassbouss** [comment]
@jpiesing this is already reflected in https://github.com/cta-wave/dpctf-tests/issues/18 feel free to close this issue.

**Comment by jpiesing** [comment]
> @jpiesing this is already reflected in [cta-wave/dpctf-tests#18](https://github.com/cta-wave/dpctf-tests/issues/18) feel free to close this issue.

@louaybassbouss I'll close the issue when I have been able to run the tests and the recordings look correct when examined frame by frame. I've not yet managed to do this.

**Comment by jpiesing** [comment]
Seems to be OK.
