### ISSUE TITLE
error in docker log file 

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#13]
For me, the observation framework fails to post results with error code 500 from the test runner. The following can be found in the docker log file (note this is **after** changing the ownership of the results directory from root to myself, rebuilding docker & re-starting it).

1780a1781,1790
> DEBUG:web-platform-tests:GET /_wave/api/results/6d18b186-a451-11eb-a6ec-0242ac110002/avc/json
> DEBUG:web-platform-tests:Found handler WaveHandler
>   File "/home/ubuntu/DPCTF/tools/wave/network/api/results_api_handler.py", line 95, in download_results_api_json
>     blob = self._results_manager.export_results_api_json(token, api)
>   File "/home/ubuntu/DPCTF/tools/wave/testing/results_manager.py", line 478, in export_results_api_json
>     file_path = self.get_json_path(token, api)
>   File "/home/ubuntu/DPCTF/tools/wave/testing/results_manager.py", line 362, in get_json_path
>     browser = parse_user_agent(session.user_agent)
> ERROR:wave-api-handler:Failed to download api json: AttributeError: 'NoneType' object has no attribute 'user_agent'
> DEBUG:web-platform-tests:500 GET /_wave/api/results/6d18b186-a451-11eb-a6ec-0242ac110002/avc/json (None) 0

**Comment by jpiesing** [comment]
I'm uncomfortable considering this as an enhancement. There appears to be a significant risk of this catching people who don't notice it in the documentation. The failure mode is not obviously linked to the cause of the problem and likely the wrong component would be blamed. A simple check that the results directory is writable would seem to be a sensible precaution - like code checking its inputs are valid before executing.

**Comment by louaybassbouss** [comment]
@jpiesing I just discussed with @FritzHeiden he is using the label `enhancement` as a usability improvement of the test suite and NOT as a priority, but to avoid confusion I will remove it.

**Comment by louaybassbouss** [comment]
@FritzHeiden it is possible during the start of the docker container to raise an error (and show  a user friendly message with a link to the documentation) if the results folder is not writable?

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/116992314-1c238200-acd6-11eb-8f1b-0f25c55e6296.png)

This is now implemented. When starting the container, a check for the results directory ownership is performed. If it is misconfigured, a warning message is displayed in the logs.

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden. @jpiesing if you are happy with this solution, feel free to close this issue. If you like to provide another text for the warning please provide it in the comment and Fritz can update it.

**Comment by jpiesing** [comment]
@FritzHeiden Thanks.

It's only visible if you do 'docker logs dpctf' and even then, it's buried in the middle of a long stream of log information. In my example, this is on line 971 of 1800 lines of log information. I don't think people will even see it.

Is there any way to make this **visible** during the install process & not in the docker logs?
Is there any way to make this a fatal error?

**Comment by louaybassbouss** [comment]
> @FritzHeiden Thanks.
> 
> It's only visible if you do 'docker logs dpctf' and even then, it's buried in the middle of a long stream of log information. In my example, this is on line 971 of 1800 lines of log information. I don't think people will even see it.
> 
> Is there any way to make this **visible** during the install process & not in the docker logs?
> Is there any way to make this a fatal error?

Good point Jon I discussed this with @FritzHeiden today. The simplest solution is to exit with this error message if the folder is not writable. If the folder is not writable, I don't see any reason why we need to start the Test Runner. wdyt?

**Comment by jpiesing** [comment]
> Good point Jon I discussed this with @FritzHeiden today. The simplest solution is to exit with this error message if the folder is not writable. If the folder is not writable, I don't see any reason why we need to start the Test Runner. wdyt?

The error message is a little more specific than the directory just being writable, it's that the directory needs specific ownership. Ideally the test and the error message if it fails would be consistent. I agree about not starting the Test Runner.

**Comment by FritzHeiden** [comment]
@jpiesing The test runner now won't start if the results directory is not writeable. The error message is accessible via `docker logs -f` command.

**Comment by jpiesing** [comment]
> @jpiesing The test runner now won't start if the results directory is not writeable. The error message is accessible via `docker logs -f` command.

Presumably there's a reason why you've not included this in build.sh where the error message would be more accessible? People less familiar with docker won't know about 'docker logs'.

**Comment by FritzHeiden** [comment]
The `./build.sh` script is only for creating the image. In case someone got the image without building it by oneself, you wouldn't run the checking script at all. The logs when running the container are hidden when running it in background. The `README.md` also states that and lists the command to view the logs.  
To make this more clear, I will add how not to run the container as daemon, in which case the logs will be visible right away.

**Comment by jpiesing** [comment]
> To make this more clear, I will add how not to run the container as daemon, in which case the logs will be visible right away.

There should be a very strong recommendation to not run the container as daemon when someone is getting started.

**Comment by FritzHeiden** [comment]
The `README.md` is now updated, including your feedback

**Comment by jpiesing** [comment]
> The `README.md` is now updated, including your feedback

How about "Once the docker container is repeatedly running correctly, it may be run as a daemon using the `-d` flag:"?

**Comment by FritzHeiden** [comment]
`README.md` updated

**Comment by jpiesing** [comment]
Good.
