### ISSUE TITLE
flag error if IP address in host_override is no longer valid

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#15]
DHCP lease renewal may result in the IP address in config.json no longer being valid.
Error behaviour when this happens should be more obvious.

**Comment by FritzHeiden** [comment]
@jpiesing I added script that checks the IP using `ping` before starting the test runner when running the container.

**Comment by jpiesing** [comment]
I've not managed to reproduce the problem. Closing.
