### ISSUE TITLE
test revision number and runner revision number for build.sh

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#16]
The current descriptions of the test revision number and runner revision number are unclear but the most likely interpretation is unfriendly.

![image](https://user-images.githubusercontent.com/8490792/117657032-5f2f9a80-b199-11eb-9be5-28e884d83790.png)

A very literal interpretation of "some value that differs from previous builds" would require the documentation of which values have been used on a particular system. Even just interpreting this as "a higher value than last time" would require documenting the highest value used on each system.

Is there a reason why a simple boolean is not used?

**Comment by jpiesing** [comment]
> Agree . What about using the flags `clear_runner_cache` (triggers the download of the [DPCTF test runner](https://github.com/cta-wave/dpctf-test-runner)) and `clear_tests_cache` (triggers the download of [dpctf-tests](https://github.com/cta-wave/dpctf-tests))?

Or just 'reload_test_runner' and 'reload_tests'?

**Comment by louaybassbouss** [comment]
> > Agree . What about using the flags `clear_runner_cache` (triggers the download of the [DPCTF test runner](https://github.com/cta-wave/dpctf-test-runner)) and `clear_tests_cache` (triggers the download of [dpctf-tests](https://github.com/cta-wave/dpctf-tests))?
> 
> Or just 'reload_test_runner' and 'reload_tests'?

@FritzHeiden please use these flags

**Comment by jpiesing** [comment]
> Fixed

Confirmed.
