### ISSUE TITLE
failed clean installation with no obvious error message

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#18]
I needed to do a clean installation on a different PC. 
There were no obvious error messages during the process but the installed image doesn't work properly as you can see here.

![image](https://user-images.githubusercontent.com/8490792/119795514-d6269c00-bed8-11eb-97b4-da027fdccb42.png)

A logs file is attached. The 404s at the end look suspicious.

I have gone back to the beginning and re-done the steps starting from ./build.sh and it didn't make any difference.

[docker-logs-desktop-2021-05-27.txt](https://github.com/cta-wave/dpctf-deploy/files/6552521/docker-logs-desktop-2021-05-27.txt)

**Comment by FritzHeiden** [comment]
This problem seems to arise when accessing `http://web-platform.test:8000/_wave` instead of `http://web-platform.test:8000/_wave/index.html`. I will investigate further to see if this can be avoided.

**Comment by louaybassbouss** [comment]
`http://web-platform.test:8000/_wave/` should work as well

**Comment by FritzHeiden** [comment]
I pushed a fix. Now `http://web-platform.test:8000/_wave` returns with an HTTP status 404

**Comment by jpiesing** [comment]
http://web-platform.test:8000/_wave/index.html is confirmed to be OK.
