### ISSUE TITLE
no media plays with clean install & no error messages

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#19]
I'm trying a clean install & no media plays, there are no error messages. This is true for both firefox on Linux and chrome on a phone. The QR code drawn by the app is shown but that's it.
[dpctf-docker-logs-2021-05-31.txt](https://github.com/cta-wave/dpctf-deploy/files/6570033/dpctf-docker-logs-2021-05-31.txt)

**Comment by FritzHeiden** [comment]
![image](https://user-images.githubusercontent.com/9076000/120193895-3c832580-c21d-11eb-8f92-2157cc89fa01.png)

Content plays for avc 15 30 60 online group.

Did you try to use the local content? This may reduce the number of potential problems.

**Comment by jpiesing** [comment]
@FritzHeiden Was your run from a clean install?

**Comment by FritzHeiden** [comment]
Yes, I reran the build script with reload parameters

**Comment by jpiesing** [comment]
I wonder if the installer is not installing everything it should. Here's firefox network debug. The test is failing to load favicon.ico and never even requesting the media.

![image](https://user-images.githubusercontent.com/8490792/120203380-f1224480-c227-11eb-8def-9b83028caeb2.png)

**Comment by jpiesing** [comment]
It turns out the screendump is only after a page reload. Here's a full log of a test run.

[192.168.40.43_Archive [21-05-31 15-56-47].zip](https://github.com/cta-wave/dpctf-deploy/files/6570727/192.168.40.43_Archive.21-05-31.15-56-47.zip)

The .zip file includes a .har file - a JSON file you can load into the firefox debugger or other tools. There's still no sign of it attempting to load any media files.

**Comment by jpiesing** [comment]
![image](https://user-images.githubusercontent.com/8490792/120204954-ae616c00-c229-11eb-9985-b63e415f520d.png)

**Comment by jpiesing** [comment]
![image](https://user-images.githubusercontent.com/8490792/120205050-ccc76780-c229-11eb-8a14-27c3cfcaa824.png)

**Comment by jpiesing** [comment]
I've just done it on a different computer & get the same results.
[192.168.40.54_Archive [21-05-31 16-54-09].zip](https://github.com/cta-wave/dpctf-deploy/files/6571011/192.168.40.54_Archive.21-05-31.16-54-09.zip)
![image](https://user-images.githubusercontent.com/8490792/120211248-ff289300-c230-11eb-96ca-c593b9572544.png)

**Comment by andyburras** [comment]
May be related... I discovered with a updating to "latest" dpctf_deploy last week that I had no media playing in Test Runner. I think the tests.json and test-config.json are out of sync. The test-config falls back to a generic config of 'total_representations' which equals 3, but the actual number of representations in the MPDs is different.

No error gets logged, but digging around I did see a subtest result of "Error: Provided total representations do not match MPD total representations of 8\"

**Comment by FritzHeiden** [comment]
@andyburras I updated the `test-config.json` and removed the constraints.

**Comment by jpiesing** [comment]
> @andyburras I updated the `test-config.json` and removed the constraints.

Unfortunately I still don't get any media segments - as before there's no sign of the test code even attempting to fetch them.

**Comment by FritzHeiden** [comment]
@jpiesing Are there any error messages in the test results?

**Comment by jpiesing** [comment]
> @jpiesing Are there any error messages in the test results?

Exactly where do you mean? There's nothing in the Firefox developer console except for the 404 due to favicon. 

Here's the output of 'docker logs dpctf'

[dpctf-logs-2021-06-01.txt](https://github.com/cta-wave/dpctf-deploy/files/6575260/dpctf-logs-2021-06-01.txt)

Exactly where would such error messages appear?

**Comment by FritzHeiden** [comment]
After starting the session via `configuration.html`, the page redirects to the results page for that test session. After all tests have run in a group you can click on the groups report button in the results table. There you can see the error that caused a test to fail.

I recently pushed some updates to the tests that additionally print all caught errors into the console.

**Comment by jpiesing** [comment]
It started working for me with the most recent push. I'll close this issue at the end of today if it keeps working.

@FritzHeiden What do you mean by "you can click on the groups report button in the results table. "?

Do you mean the button shown in red here?

![dpctf-report-2021-06-01 png](https://user-images.githubusercontent.com/8490792/120324182-a1568280-c2e6-11eb-9245-5b29b83b8004.png)

Clicking on that does nothing at all.

**Comment by FritzHeiden** [comment]
Yes, this button should open the test report:
![image](https://user-images.githubusercontent.com/9076000/120325396-e202cb80-c2e7-11eb-9bbf-6c89219bd9af.png)

**Comment by jpiesing** [comment]
This appears to be a firefox issue - the results page is being caught by the Firefox popup blocker. 
Firefox 88 on Windows triggers a popup-blocker message and asks me if I want to permit the popup.
Firefox 88 on Linux silently blocks the page. Game over.

**Comment by jpiesing** [comment]
Tests now run on both my phone and my tablet so I'm closing this. I don't know which change caused it to start working.
