### ISSUE TITLE
update import.sh as database.json has moved to github

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#21]
import.sh needs to be updated as database.json has moved from Akamai to github due to the caching issues.

See https://github.com/cta-wave/Test-Content/issues/15

**Comment by louaybassbouss** [comment]
@jpiesing the import.sh script now uses the new location of database.json --> https://raw.githubusercontent.com/cta-wave/Test-Content/master/database.json. The download script is also updated to support the new JSON structure in database.json. Please check and close this issue if the script works on your side.

**Comment by jpiesing** [comment]
OK.
