### ISSUE TITLE
import.sh always downloads encrypted content

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#23]
For the un-encrypted content, import.sh checks if the content is already downloaded and doesn't download it again.
For the encrypted content, import.sh always downloads the content regardless.
Is this intentional or a bug?

**Comment by FritzHeiden** [comment]
I was able to reproduce the issue. It's not the download script that is misbehaving, we expect the zip files to have a specific file structure. We derive this structure from the MPD path in the database json and check if it exists in the filesystem.

The zip structure has to be equal to the 3 parent directories of MPD URL. For example, the t1 MPD URL is `https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t1/stream.mpd`, its zip content has the structure `/avc_sets/15_30_60/t1`. On the other hand, t1-cenc has the MPD URL `https://dash.akamaized.net/WAVE/vectors/2021-06-11/avc_sets/15_30_60/t1-cenc/stream.mpd`, however, its zip content has the structure `/t1-cenc`.  
This zip structure is maintained when extracting it to the content directory, so the script cannot detect that its already there.

@rbouqueau could you please ensure this structure for the cenc zip files?

**Comment by rbouqueau** [comment]
Sure. This is done manually at the moment, I'll be careful to make it consistent with the content in clear.

**Comment by rbouqueau** [comment]
Could you please retry and let me know if this now fixed?

**Comment by jpiesing** [comment]
It looks OK to me.
@FritzHeiden If it OK to you then please close it.

**Comment by louaybassbouss** [comment]
> It looks OK to me.
> @FritzHeiden If it OK to you then please close it.

Ok for us ... closing this issue
