### ISSUE TITLE
Loading and Running Test Runner on Windows computer

### ISSUE THREAD

**Issue by gitwjr** [cta-wave/dpctf-deploy#25]
Trying to test the runner on Windows computer following the ReadMe. I can build the Docker files (build.sh) but when I try to import content (import.sh) it fails. Need more complete documentation since it is clear I am doing something wrong but after many hours it still eludes me.   
Docker Logs:
CRITICAL:web-platform-tests:Failed to connect to test server on http://web-platform.test:58483/. Please ensure all the necessary WPT subdomains are mapped to a loopback device in /etc/hosts.
See https://web-platform-tests.org/running-tests/from-local-system.html#system-setup for instructions.
ln: failed to create symbolic link './*': File exists
stat: cannot stat '/home/ubuntu/DPCTF/results': No such file or directory
stat: cannot stat '/home/ubuntu/DPCTF/results': No such file or directory
=== ERROR ================================================================
= Ownership or permissions of results directory not properly configured. =
= Set ownership to 1000:1000 and make directory writable! =
==========================================================================

**Comment by louaybassbouss** [comment]
Thanks @gitwjr we will check and come back ASAP to you.

**Comment by FritzHeiden** [comment]
Could you please provide more information on what actions you performed and when the error occurred?

**Comment by gitwjr** [comment]
I use an external drive (D) for the files. First I added Windows WSL2 to my Win10 OS. Installed Python 3.9.7 on the D drive in its own folder. Created sub-folder Deploy_Files and under it subfolder dpctf-deploy-master and installed Git and Docker Desktop in it. Docker Desktop shows it starts under WSL2. After figuring out the need to add paths, etc., I was able to run "build.sh master latest" successfully. I then tried to import using import.sh. The errors shown in Docker logs above occurred after running inport.sh. The error in Bash is: 
./import.sh: ./download-content.py: /usr/bin/python3: bad interpreter: No such file or directory . 

I've tried deleting and rebuilding but always the same result. I also (recently) installed Ubuntu 20.4, and tried many other things without success (too numerous to list). I checked the UID on Git installed on D drive. It comes up with my own. I changed several folders to me as owner. When I check UID on Ubuntu bash it shows UID 1000 but Git Bash installed on D still shows my UID.  I can't change the Ubuntu bash directory to my D drive for some reason that still escapes me. And I have no idea how to see which UID the directories in the container in docker use (as the ReadMe suggests). 

It appears the ReadMe assumes a level of expertise in these packages (or at least the order and options used when installing and running them) that I do not have. My next step would be to uninstall everything and reinstall but I don't want to do that until I have a better idea of the order and options, the settings and paths needed, etc., to do it correctly. Sorry for my lack of experience with these packages. But I have asked some very experienced people, including one who is a Python (and much more) guy. None have been able to help due to their lack of specific knowledge of Docker, and Linux on Windows machines. Those with Linux experience either run MAC or dual boot. My best guess is there are host, sharing, and permissions needed that I am not setting correctly (and perhaps more).

**Comment by gitwjr** [comment]
I am now able to import content. After uninstalling Ubuntu, Docker Desktop, and the containers, etc., I reinstalled them all along with the latest Windows Terminal. The missing steps were to 
1) Add the PATHs to the Docker Master folder after downloading and saving it on D drive. Done in the Windows System Environment Variables - PATH - New  
2) Opening Windows Terminal and selecting Ubuntu on the drop down. This changed UID to 1000. Everything else was done from here so the UID was correct. First major problem I had. 
3) Changing directory to the path to the Docker Master folder cd /mnt/d/... containing the commands, etc. This was the second step I couldn't figure out. I had done it before but was running under wrong UID. 
4) Run build.sh master import, docker-compose, import, etc., per ReadMe and the rest of the instructions there. 
I now have content. 
I assume the above is obvious to those more familiar with doing these things. But it took me a long time to figure it all out and get them done in the right order. 
Next step is to run tests. 
Question: Do I need a camera to run the tests? Can I see something is working if I run without a camera?

**Comment by jpiesing** [comment]
>     4\. Question: Do I need a camera to run the tests? Can I see something is working if I run without a camera?

No. You can run the tests on the same PC, a different PC, a phone or even a TV if you have a way to point a browser on the TV at a URL.

The test will run on the device. I'll send you a recording of one test running on a phone for comparison.

**Comment by jpiesing** [comment]
You should not be generating tests.
The already generated tests are run by pointing a browser at the web server running in the docker instance.

**Comment by gitwjr** [comment]
Once I got the build and import completed I simply followed the directions on Docker Deploy to run the test. I tried a number of runs on both Edge and Chrome using http://localhost:8000/_wave/index.html, and configured the session to use various APIs (some using entire sets and some with just one or a few APIs within a single set) for 60 Hz and tried just local, just online or both. Each time regardless of the API(s) and browser I got no pass or failed tests. Just a single timeout after 5 minutes (300 seconds) and then it appeared to keep running but with zero pass, fail or additional timeouts. I left it running for over 2 hours one time. 
At that point I though that perhaps I needed to generate tests or use the generated tests so I tried to do that but was unable to do it successfully. That's where I am at this point. I likely am missing some path in system environment variables but can't figure out since I've added paths to pretty much everything I can think of.

**Comment by gitwjr** [comment]
Downloaded the test runner master and saved in the same main folder as others. Added the path to the dpctf-test-runner-master to System Environment Variables. No change. All APIs/tests I configure result in first test timeout and no others are run. It is unclear where to go from here. Results just says 1 test timeout after 300 seconds and then just continues running with no pass, fail or further timeouts of tests.  It is unclear where to go from here.

**Comment by FritzHeiden** [comment]
We do not intend to support running the test runner on Windows using WSL. I added some scripts and updated the documentation on how to setup the test runner on Windows without using WSL. With this method I was able to execute tests properly on my Windows machine. Please try again with the new scripts and let me know if you have any questions.

**Comment by gitwjr** [comment]
Does this mean I should exit WSL, delete the Docker Container and images, content folder files, and the dpctf-deploy-master files, before building and importing and then running the tests?

**Comment by gitwjr** [comment]
Do I need to delete WSL2? Appears Docker Desktop automatically uses it when it is installed.

**Comment by FritzHeiden** [comment]
I don't think you would have to delete WSL2 as docker shouldn't exclusively work for either WSL2 or standard Windows.

**Comment by louaybassbouss** [comment]
@gitwjr what @FritzHeiden did is to get the Test Runner working on Windows and updated the documentation. We need now to investigate why all tests are timed out on your side (The Test Runner Docker seems to work since you can open the landing page). Can you please start the Test Runner page in Chrome Browser, open the Developer Console while a Test is running and send screenshots ( from Console and Network Tabs in the developer console). If you prefer to setup a call and do the debugging together please let us know.

**Comment by gitwjr** [comment]
I deleted the container/image and restarted Docker without the WSL2 box checked. None of the paths show up in bash $PATH. Rechecked the box and paths are there. Tried to run ./build.bat master latest but returns "no such file or directory". Had to restart WSL2 to get the paths back. 
I then ran ./build.sh master latest (to make certain nothing else had broken) and docker-compose up -d and it all ran fine and created the container and image. Do you want me to re-import content (I deleted content folder already) and run the tests and send screenshots using the build./sh and fresh import? Or do you need me to use build.bat in which case I am at a loss as to how to get the paths to bash. Do I need to enter them manually in bash since they don't retrieve them from Windows environment without WSL running. 
Also, I am using Windows Terminal/Powershell with Ubuntu bash. If I switch to my installed Git Bash it switches to my Windows UID so the container directory will not be created using UID 1000.

**Comment by gitwjr** [comment]
Screenshot of Chrome Run using new build.sh and import.sh. Unable to run either using .bat extension. Went to timeout after 5 minutes. It is now at 3 hours with 33 timeouts on 33 of 36 tests. The debug message is ​ 
debug
​domain localhost
Couldn't find authed_user when parsing the JSON for PasswordVault Field Checker. 

![Screenshot 2021-09-23 142650 Developers Console page during run](https://user-images.githubusercontent.com/15801730/134563496-592d0fbe-d6b2-4279-ad6b-17bafb6f7fa4.png)

**Comment by gitwjr** [comment]
Developers console after completion of run. Note, this is the first time it ran all of the tests although all timed out. 

![Screenshot 2021-09-23 175627 Developers Console page after run](https://user-images.githubusercontent.com/15801730/134589679-a2c0cbbb-8865-432d-b75b-df59b467259d.png)

**Comment by gitwjr** [comment]
@louaybassbouss and @FritzHeiden determined that the issue was with the URL in the import json pointing to the wrong content download location. We tested using online content rather than local content for the Runner and it worked as long as the browser continued to display the content playing. If I left the browser window (Chrome) to view the runner landing page/results on a different tab the browser appears to stop playout resulting in a timeout. You must move the landing page/results to a new window and leave the video page displayed. The browser page showing the test video stopped with a "Your connection is not private" error message showing "Not secure | https://web-platform.test:8443/avc_15_30_60-2021-07-07-online/playback-of-encrypted-content-https__t1-cenc.html?token=c2515aa4-211f-11ec-a3be-0242ac110002&timeout=300000&https_port=8443&web_root=/_wave/&mode=auto&&&redirect_time=5" with a strikeout through "https". That test timed out. I instructed Chrome to ignore the error and the session completed immediately.  Apparently that was the last test. Results showed 64 Pass. 3 timeouts: 2 timeouts were due to leaving the test page, one for the https "Not Secure" message which appears to have been the test file "/avc_15_30_60-2021-07-07-online/playback-of-encrypted-content-https__t1-cenc.html". I have Chrome set to message when a page does not support https which appears to have been the reason for the error. 
 
I will reimport the content and test locally. I will report the results when complete.

**Comment by FritzHeiden** [comment]
I updated the `import.sh` script to use a static URL to the stable content.

**Comment by gitwjr** [comment]
After reimporting the content the test using the re-imported local content is running fine. The new URL provided by @FritzHeiden to replace the one in the import json file fixed the local content issue.    70 of 70 tests passed on 35 test files using avc_15_30_60-2021-07-07-local. Success!

**Comment by louaybassbouss** [comment]
Thanks @gitwjr for the feedback and happy to see the test runner is working on Window as well. 
@jpiesing  FYI there was an issue that the generated DPCTF Tests were not compatible with the latest version of [database.json](https://raw.githubusercontent.com/cta-wave/Test-Content/master/database.json).  To avoid this, we updated the [import script](https://github.com/cta-wave/dpctf-deploy/blob/master/import.sh) to use a version of database.json compatible with the generated tests. 

@gitwjr feel free to close the issue if all your questions are answered.

**Comment by jpiesing** [comment]
@gitwjr @louaybassbouss Please consider if the documentation should be updated to include anything specific about Windows.

> FYI there was an issue that the generated DPCTF Tests were not compatible with the latest version of [database.json](https://raw.githubusercontent.com/cta-wave/Test-Content/master/database.json). To avoid this, we updated the [import script](https://github.com/cta-wave/dpctf-deploy/blob/master/import.sh) to use a version of database.json compatible with the generated tests.

Does a bug need to be filed about this? Is this a problem with the database.json file or with the tests or is more investigation needed?

**Comment by FritzHeiden** [comment]
@jpiesing When generating the tests, the URL to the most recent content at the time of generating is put into the test files. When deploying, these test files are pulled from the repository and the most recent content at the time of deploying is downloaded. As soon as there is new content, there is always the chance that the test files are not yet updated to contain the URLs to the new content. Now, if someone deploys the test runner, the test will not work due to the mismatch of local content and the URLs in the test. Therefore, the approach is to manually update the URL in the `import.sh` script when the generated tests are also updated, rather than always pointing towards the most recent database.json.

**Comment by jpiesing** [comment]
> @jpiesing Therefore, the approach is to manually update the URL in the `import.sh` script when the generated tests are also updated, rather than always pointing towards the most recent database.json.

Who needs to update this? You? Can this be automated so that someone doesn't have to remember to do it? Is it possible to have import.sh generate an error if the update hasn't been done? I really dislike manual processes that someone has to remember to do & where it's not obvious if this hasn't been done.

**Comment by FritzHeiden** [comment]
> Now, if someone deploys the test runner, the test will not work due to the mismatch of local content and the URLs in the test.

Actually, the problem was, that the [new database.json](https://raw.githubusercontent.com/cta-wave/Test-Content/4447bc47ca97f284ef5c3cdd0353e96408506ec0/database.json) did not specify content for e.g. 15_30_60/t1, so tests depending on it failed. Another question that arises is, whether or not it is intended for the new database.json to not include this content.

**Comment by jpiesing** [comment]
> Actually, the problem was, that the [new database.json](https://raw.githubusercontent.com/cta-wave/Test-Content/4447bc47ca97f284ef5c3cdd0353e96408506ec0/database.json) did not specify content for e.g. 15_30_60/t1, so tests depending on it failed. Another question that arises is, whether or not it is intended for the new database.json to not include this content.

Please report a bug on that in the test content generation project so we can identify if this is a technical issue, an operational issue or a misunderstanding of what is expected.

**Comment by louaybassbouss** [comment]
> Please report a bug on that in the test content generation project so we can identify if this is a technical issue, an operational issue or a misunderstanding of what is expected.

@jpiesing the issue is database.json is now fixed. @FritzHeiden  can you change the URLs in the download script to point to the database.json from main/master?

**Comment by gitwjr** [comment]
Ran 3 more sets of tests all using Chrome on PC and phone, each including the original 3 tests that timed out. 
Results and actions.
First test appears to have had interruptions from browser flagging non-https site. 
![Screenshot 2021-10-16 105323 3 failed tests](https://user-images.githubusercontent.com/15801730/137593239-dc17ea40-1642-4ab7-b717-cdab8d260f05.png)
Turned off safe browsing protection
Second test had one timeout. Screen froze at 57.933. Some of the other videos would pause at times during the test and then resume. 
![Screenshot 2021-10-16 110723 one timeout](https://user-images.githubusercontent.com/15801730/137593376-f2b36b55-ebc1-4af6-809e-0ae5b7c027eb.png)
Added several additional tests for the 3rd run. All passed. 
![Screenshot 2021-10-16 111819 all pass](https://user-images.githubusercontent.com/15801730/137593420-d880e499-5d88-42ad-ace5-094b479b60a3.png)

**Comment by gitwjr** [comment]
In working on the OF I had to re-build the TR. I built it using the .bat build and import per instructions to get the latest TR. But when I try http://localhost:8000/_wave/index.html on Chrome, Firefox and Edge it returns the following (or equivalent). 

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

Any thoughts? I've searched the web for fixes but none have worked.

**Comment by gitwjr** [comment]
I also uninstalled and reinstalled Docker Desktop again as I was getting errors when trying to recreate the container after the build.

**Comment by louaybassbouss** [comment]
> In working on the OF I had to re-build the TR. I built it using the .bat build and import per instructions to get the latest TR. But when I try http://localhost:8000/_wave/index.html on Chrome, Firefox and Edge it returns the following (or equivalent).
> 
> This site can’t be reachedlocalhost refused to connect. Try:
> 
> Checking the connection Checking the proxy and the firewall ERR_CONNECTION_REFUSED
> 
> Any thoughts? I've searched the web for fixes but none have worked.

@gitwjr  can you confirm that you are using window without WSL?

**Comment by gitwjr** [comment]
Its not clear to me what you mean running under window without WSL. Docker Desktop requires WLS to load. When I turn off WSL it refuses to start. 

I uninstalled and reinstalled Docker Desktop and deleted the TR (again) and rebuilt it and reimported all using powershell Windows screen to run the .bat files. TR ran successfully and passed a number of tests. However, the powershell remained showing the progress of the runs. I stopped the last run using the TR UI command Stop. But the powershell screen remained showing the progress. Closed out the browser pages. Powershell still not giving a prompt for any commands. I had to use the Ubuntu terminal (on powershell) to stop the docker (docker stop dpctf). Powershell then returned to a prompt. But when I restarted the docker (docker start dpctf) the container now shows dpctf-deploy-master starts with alternatively flashing "running" and "other" before settling on "other". And now the browser refuses to connect again. Seems that there is an interaction between Windows and Linux that alters the container. It late so I will have to take this up again later.

**Comment by gitwjr** [comment]
I totally wiped my system (Ubuntu, Python, Docker, ZBar, and the WAVE components and reinstalled/rebuilt the Test Suite from scratch. The only thing I didn't uninstall was WSL2. Everything works fine with just a couple of minor hiccups. I ran the OF on a new test run and there were no problems either. I had 5 fails but that could be due to the video quality and other issues. The key point is the process works. I am documenting the steps I used in detail now. I think we can close this issue.

**Comment by gitwjr** [comment]
I rewrote the ReadMe for Setup on Windows using WSL2. It is the procedure I used after wiping and uninstalling everything and starting from scratch. It also includes the OF procedures so it may need to be either split in two parts or linked to from both main ReadMe pages. Please review and comment.
[Setup on Windows using WSL2.docx](https://github.com/cta-wave/dpctf-deploy/files/7653078/Setup.on.Windows.using.WSL2.docx)

**Comment by gitwjr** [comment]
Note there are several open questions at the top of the document that probably should be addressed.

**Comment by gitwjr** [comment]
It appears I deleted the questions for the write-up since they were not appropriate for the instructions. 
1) In the TR ReadMe, there is a section labeled "Edit Hosts File. It is required to map a set of domains to local host using the hosts file.". There are no instructions as to what needs to be edited. I didn't edit anything after the wipe and reinstall but entries may have remained from the prior installs. Need to expand on what to do/look for. 
2) When installing Docker there is a section in the Docker Instructions https://docs.docker.com/desktop/windows/wsl/#best-practices. "To get the best out of the file system performance when bind-mounting files, we recommend storing source code and other data that is bind-mounted into Linux containers (i.e., with docker run -v <host-path>:<container-path>) in the Linux file system, rather than the Windows file system. You can also refer to the recommendation from Microsoft." It is unclear to me what this means. I read the Microsoft link but it did not help. Some expansion on what to do would be helpful. As noted I ran everything under Windows PowerShell not a Linux Terminal and it appears to work well but this might account for why at times the Container shows "other" and some files cannot be accessed without deleting the container and image and reinstalling Docker.

**Comment by gitwjr** [comment]
The Docker ReadMe notes "It is highly recommended to use Linux for production. Windows and MacOS should be used for experimental purposes only!". 
Linux use is already fully documented. Windows is documented. We can launch with the current documentation. 
Close.
