### ISSUE TITLE
https needed

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-deploy#29]
The tests with encrypted content  using EME feature requires secure context (valid https).
The project does not include the https protocol.
Connected to https://redmine.hbbtv.org/issues/12374

**Comment by louaybassbouss** [comment]
> The tests with encrypted content  using EME feature requires secure context (valid https).
> 
> The project does not include the https protocol.
> 
> Connected to https://redmine.hbbtv.org/issues/12374

Test Runner supports https as well. @FritzHeiden will provide details.

**Comment by Lis-TV** [comment]
Propose to extend manual with the details.

**Comment by louaybassbouss** [comment]
> Propose to extend manual with the details.

@Lis-TV  HTTPs will be automatically selected since the EME Tests include https in the filename. The TestRunner (TR) will serve those test via https. It is important for https to start the TestRunner via domain web-platform.test and not via IP of the TR.  What you need to do is to define in your local network a DNS Entry for the domain web-platform.test pointing to the IP of the TR.

**Comment by jpiesing** [comment]
@Lis-TV Please could you be more specific about why you say "The project does not include the https protocol.". What made you think this? Is there some specific text somewhere?

**Comment by Lis-TV** [comment]
The pages are displayed fine if I am using http:// protocol
When I am opening 127.0.0.1:8000 (or hbbtv.test:8000 with DNS) I am receiving ERR_SSL_PROTOCOL_ERROR.

I think that the problem is the browser do not have access to certificate files.

How to configure solution to add private and public certificate files (both .crt and .key). 
For example in case of Apache, I need to set location using SSLCertificateKeyFile and SSLCertificateFile in httpd-ssl.conf, and the certificates must be at given location.

**Comment by Lis-TV** [comment]
The test have to be run by the test runner, not manually. It works.
