### ISSUE TITLE
Port 53 for udp

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-deploy#30]
"53:53/udp" from docker-compose.yml

The port number 53 is normally reserved by system for DNS. Hense Test Runner cannot set up using own DNS with this port directly as the port 53 is already in use, so you'll get an error similar to this: "listen tcp 0.0.0.0:53: bind: address already in use". 
The port 53 can be used by test runner once the user manully free up the port by stoping systemd-resolved from using port 53.
However, can test runner using another port number to make it simpler to set up?

**Comment by louaybassbouss** [comment]
@yanj-github if you use your own DNS server, then you can safely remove/comment this line "53:53/udp" from docker-compose.yml . You can also edit it if you want to use another port different than the default one. But most platforms only allow to use the default DNS port 53.

**Comment by yanj-github** [comment]
@louaybassbouss Thanks.
Just to confirm that, when 53 is reserved by system port for DNS, can I just comment this line out and test runner uses port 53 for DNS? At the moment docker set up failing with error similar to this: "listen tcp 0.0.0.0:53: bind: address already in use".

**Comment by louaybassbouss** [comment]
> @louaybassbouss Thanks. Just to confirm that, when 53 is reserved by system port for DNS, can I just comment this line out and test runner uses port 53 for DNS? At the moment docker set up failing with error similar to this: "listen tcp 0.0.0.0:53: bind: address already in use".

yes but the DNS server of the Test Runner will not be used. In this case, you need to use the existing DNS to configure the domain of the Test Runner.

**Comment by yanj-github** [comment]
> 

Thanks that is clear now. So if I have port 53 already in use. I should change "53:53/udp" from docker-compose.yml to use another port other than 53. Is this documeneted anywhere that I missed please? It would be helpful to have it docummeted please? On ubuntu port 53 is in use by system.

**Comment by jpiesing** [comment]
I'm uncomfortable about things that make the test runner hard(er) to setup or which require company IT support.

> Thanks that is clear now. So if I have port 53 already in use. I should change "53:53/udp" from docker-compose.yml to use another port other than 53. Is this documeneted anywhere that I missed please? It would be helpful to have it docummeted please? On ubuntu port 53 is in use by system.

I also use Ubuntu and port 53 is used by a local DNS proxy.



> In this case, you need to use the existing DNS to configure the domain of the Test Runner.

I think there's a lot of detail hidden under this sentence which @yanj-github may be missing.

On Ubuntu, where port 53 is used by a DNS proxy to the network-assigned DNS server, using a different port for the DNS server of the test runner is probably simpler than modifying anything relating to the network-assigned DNS server.

**Comment by louaybassbouss** [comment]
@yanj-github  @jpiesing  the line in "53:53/udp" in docker-compose.yml is now commented and the built-in DNS server is not used by default. In this case you need to configure the domain `web-platform.test` outside of the test runner. This is documented in section [Running Tests](https://github.com/cta-wave/dpctf-deploy/blob/master/README.md#running-tests). We updated the documentation to make it more clear. the domain is only important for https tests (EME API requires https) for other tests, you can access the Test Runner via its IP.

**Comment by louaybassbouss** [comment]
@yanj-github feel free to close this if issue  is solved

**Comment by jpiesing** [comment]
@louaybassbouss I think the documentation hides some detail which an average test engineer might not realise.

To fully run the WAVE DPCTF test suite requires one of the following;
- Editing the DNS server used by the device being tested to include web-platform.test 
- Setting up another DNS server which includes web-platform.test and pointing the device at this DNS server
-- This could be the DNS server included in the docker image
-- Enabling a DNS server that includes web-platform.test may be complex as OS like Ubuntu have a DNS proxy running on port 53 already.
- Most devices have (buried) UI to over-ride the default DNS server. Alternatively it may be necessary to put the device being tested on a separate network, provide a dedicated DHCP server and include the address of a DNS server supporting web-platform.test in the response of that dedicated DHCP server.

**Comment by louaybassbouss** [comment]
> 

@jpiesing fine for me are you ok to put your points in the documentation?

**Comment by jpiesing** [comment]
> 

@louaybassbouss Yes

**Comment by gitwjr** [comment]
Close. The documentation has been updated in the ReadMe. DNS is not activated by default in Docker. It can be activated. 
Reopen if we find this is a problem after we launch.
