### ISSUE TITLE
Deploy must show an EULA 

### ISSUE THREAD

**Issue by mbergman42** [cta-wave/dpctf-deploy#32]
Where WAVE allows access to the test vectors, we need to show an end user license agreement. I've created a file in dpctc-deploy called [End-User-License-Agreement.md](https://github.com/cta-wave/dpctf-deploy/blob/master/End-User-License-Agreement.md). 

When DPCTF-Deploy runs, it would be great if there were a stopping point where the install halts and displays this EULA and asks for agreement before continuing. I don't know if our structure supports this, however. 

We need to display this on the page showing the test vectors at [https://cta-wave.github.io/Test-Content/](https://cta-wave.github.io/Test-Content/) as well.

**Comment by gitwjr** [comment]
@rbouqueau to look at writing the js for Deploy page. 
 When DPCTF-Deploy runs, there needs to be a stopping point where the install halts and displays this EULA and asks for agreement before continuing. I don't know if our structure supports this, however. @mbergman42 to provide the EULA.

**Comment by rbouqueau** [comment]
I've added some minimal code as a PR.

**Comment by mbergman42** [comment]
Recommend closing this issue on next DPCTF test review meeting.

**Comment by gitwjr** [comment]
PR 36 merged. Closed.

**Comment by jpiesing** [comment]
The documentation says;

![image](https://github.com/cta-wave/dpctf-deploy/assets/8490792/7a69f5ed-aad9-483f-8597-7e6dc166304a)


When I do this and run docker-compose, I get the following error.

services.dpctf.environment.AGREE_EULA contains true, which is an invalid type, it should be a string, number, or a null

**Comment by FritzHeiden** [comment]
You would need docker-compose v2 for boolean values to work

**Comment by jpiesing** [comment]
> You would need docker-compose v2 for boolean values to work
> 
> EDIT: This also needs to be changed in the documentation

Is there an alternative? I'm using standard ubuntu 22.04 & this will really make it much harder for people to get started.

**Comment by jpiesing** [comment]
> > You would need docker-compose v2 for boolean values to work
> > EDIT: This also needs to be changed in the documentation
> 
> Is there an alternative? I'm using standard ubuntu 22.04 & this will really make it much harder for people to get started.

What about using "yes" (or "no")  rather than true or false ? Would the be compatible with docker-compose as included in Ubuntu 22.04?

**Comment by FritzHeiden** [comment]
> What about using "yes" (or "no") rather than true or false ? Would the be compatible with docker-compose as included in Ubuntu 22.04?

Yes, I am changing this right now

**Comment by FritzHeiden** [comment]
I updated to project, please have another try

**Comment by jpiesing** [comment]
> I updated the project, please have another try

It works for me. The test runner behaves correctly if the EULA is accepted and generates a reasonable message if it is not.

Can we close this issue?
