### ISSUE TITLE
import.sh does not download the newest content

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-deploy#33]
There script does not download newest test versions, i.e. https://dash.akamaized.net/WAVE/vectors/cfhd_sets/12.5_25_50/t1/2022-10-17/

**Comment by FritzHeiden** [comment]
What branch are you using?

**Comment by Lis-TV** [comment]
'dpcat-2022-10-17' 

I am using:

./build.sh --tests-branch dpcat-2022-10-17

**Comment by FritzHeiden** [comment]
Did you run the `import.sh` script as well?

**Comment by Lis-TV** [comment]
Now it works.
