### ISSUE TITLE
docker-compose.yml unclear

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-deploy#35]
The README has test_group, inside docker-compose.yml is tests,
please also describe how test_group refers to [dpctf-tests](https://github.com/cta-wave/dpctf-tests).

**Comment by FritzHeiden** [comment]
I added https://github.com/cta-wave/dpctf-deploy#adding-custom-tests and changed https://github.com/cta-wave/dpctf-deploy#mapping-new-content-into-the-container to represent the current state of how things are configured. I hope this makes more sense now.

**Comment by gitwjr** [comment]
@Lis-TV Does this address your issue? If so, please close.
