### ISSUE TITLE
improve documentation re editing hosts file and DNS when installing dpctf & docker

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#39]
The dpctf documentation is confusing about hosts. There is apparently related text in two different places that are some way apart and not linked.

![image](https://github.com/cta-wave/dpctf-deploy/assets/8490792/2d505a64-eb7f-4b73-b58a-1a567e565cd8)

and

![image](https://github.com/cta-wave/dpctf-deploy/assets/8490792/e9332945-93ea-4cdd-8c83-b17a6f95e907)

I believe these are alternatives, editing the hosts file is only needed when you're running the tests on the same machine as is running the test runner or another PC. If you're running the tests on a smart TV then the DNS changes are required.

If indeed they are alternatives then they need to be moved to be under the same heading and clearly presented as alternatives.

The text also needs to be clear enough that a test engineer can take it to their local IT person. It is currently some way off this. Perhaps you could try it on one of your local IT people and get their reaction :)

**Comment by gitwjr** [comment]
Need to clarify documentation as it is described in several places and can be confusing: See also: #41 #42.

**Comment by jpiesing** [comment]
I've reviewed QUICKSTART and I'm happy that this issue is resolved.
