### ISSUE TITLE
build.sh script needs to be run as root on ubuntu (probably other linux too)

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#4]
This may be obvious to people more familiar with docker but it wasn't obvious to me.
The ./build.sh script to install the docker image needs to be run as root on ubuntu - and presumably other Linux distros as well.
This should be added to the documentation.
The same applies to running 'docker-compose up -d'.

I have no idea if running it on Windows needs admin rights but that should be checked with someone who doesn't have admin rights.

**Comment by louaybassbouss** [comment]
@FritzHeiden can you please double check this why we need root access and if it is required please update the documentation. On mac I can create and run the image as described in the documentation. I don't have ubuntu to test.

**Comment by jpiesing** [comment]
I don't have the exact error message any more but it was very close to this one;

![image](https://user-images.githubusercontent.com/8490792/115005574-4ab4f680-9ea8-11eb-8167-ce5be856fd8e.png)

**Comment by jpiesing** [comment]
On ubuntu, /var/run/docker is read/write by root only (mode = 700) & /var/run/docker.sock is 660.
Is docker setuid root on Mac?

**Comment by louaybassbouss** [comment]
@jpiesing maybe this [reddit post](https://www.reddit.com/r/docker/comments/byciui/why_can_macos_run_docker_without_sudo_root_but_on/) provide an explanation. In any case if for Linux we need root access then we should mention it in the documentation.

**Comment by jpiesing** [comment]
The docker web site addresses this ...

https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by louaybassbouss** [comment]
> The docker web site addresses this ...
> 
> https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
> 
> I think our documentation needs to be updated to refer to this.

I am not sure how much docker details we should add in the documentation. Maybe we can add a note that docker may need to run as root if it is not configured as a non root user + Link to the docker docu. If you have another proposal feel free to create a PR ;).

**Comment by jpiesing** [comment]
> I am not sure how much docker details we should add in the documentation. Maybe we can add a note that docker may need to run as root if it is not configured as a non root user + Link to the docker docu. If you have another proposal feel free to create a PR ;).

That's fine. Some test engineers (as opposed to developers) may not have root access and may need to get IT in to do that.

**Comment by jpiesing** [comment]
> I am not sure how much docker details we should add in the documentation. Maybe we can add a note that docker may need to run as root if it is not configured as a non root user + Link to the docker docu. If you have another proposal feel free to create a PR ;).

I think the correct Link to the docker docu is this one https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

Following the instructions there worked fine for me. It's also something that test engineers without root access can easily pass on to their IT people.

**Comment by louaybassbouss** [comment]
> I think the correct Link to the docker docu is this one https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user
> 
> 
> 
> Following the instructions there worked fine for me. It's also something that test engineers without root access can easily pass on to their IT people.

Thanks @jpiesing this is great we will update the documentation on Monday and address this point.

**Comment by jpiesing** [comment]
It seems running docker on Windows requires admin access. It's worth noting that too as test engineers may not have it & may need to ask their IT people to set things up for them.

**Comment by louaybassbouss** [comment]
@jpiesing documentation is now updated we added a [Requirements](https://github.com/cta-wave/dpctf-deploy#requirements) section and mentioned how how to run docker without root/admin access. Please let us know if this issue can be closed.

**Comment by jpiesing** [comment]
Looks good.
