### ISSUE TITLE
 initial instructions for use by a Test Engineer performing the Staging testing

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#41]
Here is my current draft for my action "(2023-04-19) Mr. Piesing to write initial instructions for use by a Test Engineer
performing the Staging testing. E.g. where to find the information, what tests are to be run, etc. – Ongoing".

Here is my current draft. This issue will be edited - text in italics is editors notes, things to be done and so on.

1. Obtain the following;
1.1 a camera capable of recording 120 frames / second for minutes at a time without overheating - see https://github.com/cta-wave/device-observation-framework#camera-requirements
1.2 a PC with Linux on it (windows with WSL is not excluded but requires a significantly more experienced person doing the installation) and with the relevant hardware to read recordings from the camera (e.g. an SD card reader if the camera records onto SD cards)
1.3 a tripod or similar to hold the camera steady when pointing at the device being tested 
2. Find a room to do the tests where the camera can be pointed at the device being tested where there are no reflections on the screen of the device - see https://github.com/cta-wave/device-observation-framework#recording-environment-set-up
3. Install (or have installed for you) various software on the PC as follows;
3.1 docker, docker-compose and python3. Note that the commercial "Docker Desktop" product is not required. You can obtain the individual pieces, docker and docker-compose separately from the commercial product. 
3.2 download the dpctf-deploy github repo to the PC, either as a .zip file or 'git clone https://github.com/cta-wave/dpctf-deploy.git'
3.3 follow the instructions on https://www.github.com/cta-wave/dpctf-deploy including the headings below (noting carefully the [requirements](https://github.com/cta-wave/dpctf-deploy#requirements) for root / administrator access);
3.4 download and install the [required libraries](https://github.com/cta-wave/device-observation-framework#required-libraries) for the Observation Framework
3.5 [Download the observation framework ](https://github.com/cta-wave/device-observation-framework#obtain-the-observation-framework)
3.6 [Install the observation framework python packages](https://github.com/cta-wave/device-observation-framework#installing-the-required-python-packages)
4. Create and run the docker image on the PC
4.1 "[Create Image](https://github.com/cta-wave/dpctf-deploy#create-image)" with \<commit-id/branch/tag\> as "master" and \<image-version\> as "latest"
4.2 Ensure that the results directory is owned by 1000.1000 and is writable
4.3 Obtain the IP address of the PC and [add it to the config.json file using host_override](https://github.com/cta-wave/dpctf-test-runner/blob/master/tools/wave/docs/config.md#210-host-override)
4.4 "[Running the created image in a container](https://github.com/cta-wave/dpctf-deploy#running-the-created-image-in-a-container)" Note that the docker-compose.yml file may already be correct.
5. Download a local copy of the test content including;
5.1 [Agree to EULA](https://github.com/cta-wave/dpctf-deploy#agree-to-eula)
5.2 [Import content](https://github.com/cta-wave/dpctf-deploy#import-content)
6. [Start the container](https://github.com/cta-wave/dpctf-deploy#start-the-container)
7. If the browser on the device being tested supports direct URL entry then follow the instructions under "[Running tests](https://github.com/cta-wave/dpctf-deploy#running-tests)" and "[Run on separate DUT (TV, Mobile, etc.)] (https://github.com/cta-wave/dpctf-deploy#run-on-separate-dut-tv-mobile-etc)" to so that the device under test is showing the landing page
8. If the device being tested supports HbbTV and does not support direct URL entry then;
8.1 update the transport stream to include the IP address of the PC where the tests are installed
8.2 play that transport stream through a modulator into the device being tested and select that service so that the device under test is showing the landing page
9. Note the token from the landing page however you got to that page
10. Continue with the steps under https://github.com/cta-wave/dpctf-deploy#run-on-separate-dut-tv-mobile-etc to enter the token from the landing page into the web page of the test runner
11. Validate that the basic operation of the test runner is correct by running one of the simplest tests without the camera
11.1. Choose sequential track playback -t1
11.2
12. Once you can reliably run one test without the camera, run the same test with the camera recording;
12.1 Point the camera at the device under test
12.2 Ensure you have a good recording environment - see https://github.com/cta-wave/device-observation-framework#recording-environment-set-up
12.3 Start the camera recording
12.4 Run the test the same as you did previously
12.5 Stop the camera recording
12.6 Download the recording from the camera to the test runner PC (typically remove an SD card from the camera and plug it into an SD card reader on the PC)
12.7 Copy the recording file onto the test runner PC
12.8 Run the observation framework on the recording - see https://github.com/cta-wave/device-observation-framework#how-to-verify-the-camera-setup

The above text resulted in the following issues that can be considered blockers to release - but not to using this at the HbbTV plugfest assuming someone from Fraunhofer is participating to hold people's hands.

https://github.com/cta-wave/dpctf-deploy/issues/40
https://github.com/cta-wave/dpctf-deploy/issues/39

The following was raised but is not a blocker.

https://github.com/cta-wave/Test-Content/issues/50

**Comment by louaybassbouss** [comment]
Thanks @jpiesing as just discussed in the Testing call, we can put the documentation in the readme of this repo https://github.com/cta-wave/dpc-test-suite. wdyt?

**Comment by gitwjr** [comment]
@jpiesing @louaybassbouss 
Has this been addressed by the latest updates to the Quick Start.md or are there elements that still need to be addressed in the dpctf-deploy and Observation Framework .md instructions/code?

**Comment by jpiesing** [comment]
> @jpiesing @louaybassbouss Has this been addressed by the latest updates to the Quick Start.md or are there elements that still need to be addressed in the dpctf-deploy and Observation Framework .md instructions/code? dpctf-deploy #39 and #40 are closed and [cta-wave/Test-Content#50](https://github.com/cta-wave/Test-Content/issues/50) has been deferred.

I'm going through the  Quick Start instructions myself right now.

**Comment by jpiesing** [comment]
Here are a few other comments from doing a clean install following QUICKSTART on Linux.

1. Consider renaming the current README to something else & renaming QUICKSTART to README.
2. build.sh should check that the permissions are correct to read the docker socket and generate a helpful error message if not, e.g. referring people to the docker page for 'Linux post-install'.
3. The Windows instructions assume you're running without WSL. This means you're using Docker Desktop which is a commercial (paid) product for large companies. If someone in a large company wants to run Docker on Windows for free then they have to use WSL. For WSL, you have to follow the Linux instructions. Please add something at the start about WSL.

**Comment by louaybassbouss** [comment]
@FritzHeiden FYI

**Comment by louaybassbouss** [comment]
@gitwjr can you try to clear docker cache https://docs.docker.com/engine/reference/commandline/builder_prune/ and try again

**Comment by gitwjr** [comment]
@louaybassbouss I deleted the dpctf-dof image and ran docker builder prune --all. It took time and listed all of the steps but still did not create the device-observation-framework-main in dpctf-deploy. A search of the entire c-drive shows no such folder exists. Other ideas? I am not building the OF using the Observation Framework README instructions first (i.e. cloning the OF). The Quick Start implies that building the -dof image handles that. Is that correct?

**Comment by gitwjr** [comment]
@FritzHeiden Thanks for the clarification. When reading the Quick Start it led me to believe the OF is included in the -dof files as it says . "Following steps should be sufficient to get started with dockerized version, more details at https://github.com/cta-wave/device-observation-framework" and there is no other mention anywhere in the QS of loading the OF. I assumed the OF was now included in the Quick Start when building the -dof image. I suggest making that more clear e.g. At the beginning of phase 3  instruct the user to how to build the OF following the instructions in the OF README. Would be even better if the instructions were included in the QS guide. The OF README immediately follows cloning the OF with installing Python which I do believe is not needed anymore. I thought the necessary files are in -dof as well as loading the Mezzanine though I'd like confirmation on that.

**Comment by jpiesing** [comment]
I've been through this a couple of times and addressed the remaining issues with PR https://github.com/cta-wave/dpctf-deploy/pull/68 and new issue https://github.com/cta-wave/dpctf-deploy/issues/67.
