### ISSUE TITLE
improve HbbTV.md re domain

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#43]
HbbTV.md makes a general statement about needing a domain and a certificate but more detail and examples need to be added before it can just be given to someone from a corporate IT department.

"domain (we use yourhost.domain.tld in this document) with valid certificates are needed for some tests (EME, encrypted content)"

**Comment by louaybassbouss** [comment]
@mlasak can you check this?

**Comment by mlasak** [comment]
HbbTV.md was moved to QUICK_START.md and was merged to main branch.
Agree, with @jpiesing that more information is needed if this file alone should be enough to enable a person to deploy this project with certificates. From experience on testing events i do not recommend to use certificates as documented for web-platform-tests project for individual deployments, e.g. Tester running dpctf-deploy on local machine. This never worked reliably for me at least.

Instead, i suggest two options:

1.  HTTPS should be terminated at some corporate server, with a proxy configured to Tester's local host where the project is deployed, e.g. using Nginx proxy_pass
2. DNS based approach: firstly create SSL certificates for a domain, e.g. dpctf-tester1.domain.com and obtain the certificates to the testers machine, secondly change DNS config A-record for dpctf-tester1.domain.com and configure local test network IP (IP of testers machine and which is accessible by DUT in same network), thirdly use a simple HTTPS/HTTP proxy script to forward to test runner executed in container.

@louaybassbouss  i'll prepare a MR for this additional information

**Comment by jpiesing** [comment]
@mlasak Please take account of large organisations where the tester will need something they can pass to their IT people.

**Comment by jpiesing** [comment]
> @jpiesing yes, understood. In a nutshell this "something" the tester needs to request from IT people is quite clear:
> 
> "Provide me SSL certificates (PEM encoded key, cert and intermediate) issued for myhost.company-domain-name-or-some-test-domain.tld, whereas myhost.company-domain-name-or-some-test-domain.tld resolves to the (local) IP of myhost on which the testrunner is executed and the DUT is able connect to (which should be given if myhost and DUT are in same network)"
> 
> Specific steps how to achieve this it dependent on the IT workflows/policies of the organisations.

I was thinking more of your first option and the reference to TLS proxies and the reasons why someone might choose one option or the other.

**Comment by gitwjr** [comment]
Needs further discussion. @mlasak @jpiesing
