### ISSUE TITLE
hosts-linux.txt incorrect

### ISSUE THREAD

**Issue by Lis-TV** [cta-wave/dpctf-deploy#45]
Propose to change the order, the IP should be first, domain second.

https://tldp.org/LDP/solrhe/Securing-Optimizing-Linux-RH-Edition-v1.3/chap9sec95.html

**Comment by FritzHeiden** [comment]
Thanks for pointing that out, will fix

**Comment by FritzHeiden** [comment]
I pushed a fix for this

**Comment by Lis-TV** [comment]
Thank you. Could y please update other production branches?

**Comment by FritzHeiden** [comment]
I pushed the fix to hbbtv branch
