### ISSUE TITLE
Docker image announces itself as WMAS and not DPCTF.

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#5]
When I run a newly installed docker image, it announces itself as WMAS and not DPCTF.

![image](https://user-images.githubusercontent.com/8490792/115000897-7c778e80-9ea3-11eb-8697-387b10cb1176.png)

The github link is wrong as well.

**Comment by louaybassbouss** [comment]
Thanks @jpiesing  @FritzHeiden will fix it. 

PS: This is related to [/cta-wave/dpctf-test-runner](https://github.com/cta-wave/dpctf-test-runner) and will be fixed there. This deploy project checkouts the [/cta-wave/dpctf-test-runner](https://github.com/cta-wave/dpctf-test-runner) and [/cta-wave/dpctf-tests](https://github.com/cta-wave/dpctf-tests) projects and build the image.

**Comment by FritzHeiden** [comment]
I updated the landing page of the dpctf test runner to fix the mentioned issues

**Comment by jpiesing** [comment]
Still showing with the wrong title.

![image](https://user-images.githubusercontent.com/8490792/115235156-27917d80-a11a-11eb-8a4d-ed180e8212c0.png)

**Comment by FritzHeiden** [comment]
Did you make sure that when creating the image, the step to checkout the current dpctf test runner ran again? You can use the revision parameter to retrigger it like so:

```
./build.sh master latest 1 1
```

**Comment by jpiesing** [comment]
I thought I'd done that. Am I missing something ;

jon@orion:~/TV_Standards/CTA/wave/dpctf-test-deployment/dpctf-deploy$ ./build.sh master latest 1 1
Sending build context to Docker daemon  271.9kB
Step 1/21 : FROM ubuntu:18.04
 ---> 3339fde08fc3
Step 2/21 : RUN apt update &&    apt install git curl python python-pip virtualenv npm nodejs -y
 ---> Using cache
 ---> 5844761ce84f
Step 3/21 : ENV APP_DIR /home/ubuntu
 ---> Using cache
 ---> 28733ae7d308
Step 4/21 : RUN mkdir $APP_DIR &&    useradd -d $APP_DIR ubuntu &&    chown -R ubuntu $APP_DIR
 ---> Using cache
 ---> 440c8721a41a
Step 5/21 : WORKDIR $APP_DIR
 ---> Using cache
 ---> 0d2740ccb43a
Step 6/21 : RUN rm /bin/sh &&    ln -s /bin/bash /bin/sh
 ---> Using cache
 ---> 8cdd577fa766
Step 7/21 : USER ubuntu
 ---> Using cache
 ---> df8cd134b4fe
Step 8/21 : RUN mkdir DPCTF && cd DPCTF
 ---> Using cache
 ---> 54285fedaf9c
Step 9/21 : WORKDIR DPCTF
 ---> Using cache
 ---> 68c210a07aa1
Step 10/21 : RUN git init &&    git remote add origin https://github.com/cta-wave/dpctf-test-runner.git
 ---> Using cache
 ---> 3cca27ecd1ef
Step 11/21 : USER root
 ---> Using cache
 ---> 94f6558509b5
Step 12/21 : RUN npm install --global https://github.com/cta-wave/wptreport.git#main
 ---> Using cache
 ---> a7ae70817754
Step 13/21 : USER ubuntu
 ---> Using cache
 ---> bd65153dd723
Step 14/21 : ARG commit
 ---> Using cache
 ---> f118cb40a97f
Step 15/21 : ARG runner-rev
 ---> Using cache
 ---> 4db7fbc701eb
Step 16/21 : RUN git fetch origin $commit
 ---> Running in 274dcd5c7dfe
From https://github.com/cta-wave/dpctf-test-runner
 * branch                  master     -> FETCH_HEAD
 * [new branch]            master     -> origin/master
Removing intermediate container 274dcd5c7dfe
 ---> f82ca714c27f
Step 17/21 : RUN git reset --hard FETCH_HEAD
 ---> Running in e20874dcf5c6
Checking out files: 100% (68034/68034), done.
HEAD is now at bb337d777c Updated landing page
Removing intermediate container e20874dcf5c6
 ---> 326fdd1b75f7
Step 18/21 : ARG tests-rev
 ---> Running in 0f11a7c3fd2a
Removing intermediate container 0f11a7c3fd2a
 ---> 1558d0049610
Step 19/21 : RUN ./import-tests.sh
 ---> Running in 04f684198626
Removing all test files ...
rm: cannot remove 'MANIFEST.json': No such file or directory

Importing DPCTF tests ...
Cloning into 'dpctf'...

Start WAVE server using ./wpt serve-wave
Removing intermediate container 04f684198626
 ---> eac47767f4f9
Step 20/21 : EXPOSE 8000
 ---> Running in 2372da69d174
Removing intermediate container 2372da69d174
 ---> b2d280ff55c5
Step 21/21 : CMD ./wpt serve-wave --report
 ---> Running in 5f706863f580
Removing intermediate container 5f706863f580
 ---> 72656d7d3419
Successfully built 72656d7d3419
Successfully tagged dpctf:latest
jon@orion:~/TV_Standards/CTA/wave/dpctf-test-deployment/dpctf-deploy$ docker start dpctf
dpctf
jon@orion:~/TV_Standards/CTA/wave/dpctf-test-deployment/dpctf-deploy$

**Comment by FritzHeiden** [comment]
From the logs I can see that the test runner is properly fetched from github. The problem seems to be somewhere else. Maybe a caching issue in the browser? I rebuilt the image and the landing page is updated for me.

**Comment by jpiesing** [comment]
I ended up deleting the installation and starting again from scratch & it's fine now.
