### ISSUE TITLE
archive dpctf-deploy README and rename QUICK_START to README

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#64]
From the February 14th DPCTF meeting, the current README in the dpctf-deploy project should be archived and the QUICK_START renamed to README.

**Comment by louaybassbouss** [comment]
Solved by https://github.com/cta-wave/dpctf-deploy/pull/69 . @jpiesing feel free to close if ok for you.

**Comment by jpiesing** [comment]
Looks good to me.
