### ISSUE TITLE
Adding custom tests

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-deploy#66]
I think from docker-compose.yml the line 
`- ./tests:/home/ubuntu/tests ` is incorrect it should be `- ./tests:/home/ubuntu/DPCTF/tests `? 
Or maybe better to remove this line and add correct instruction in https://github.com/cta-wave/dpctf-deploy/tree/master?tab=readme-ov-file#adding-custom-tests
I think, to get this correct, "tests/new-test-group/new-custom-test.html" the "docker-compose.yml" file should has the line `- ./tests/new-test-group:/home/ubuntu/DPCTF/new-test-group`

**Comment by yanj-github** [comment]
Thanks @FritzHeiden But I cannot get it working without changing "- ./tests:/home/ubuntu/tests"  to "- ./tests:/home/ubuntu/DPCTF/tests".
The new tests not visible from the configuration page.

**Comment by FritzHeiden** [comment]
Thanks @yanj-github Will check

**Comment by FritzHeiden** [comment]
I am unable to reproduce this issue. The following works for me:

1. create a directory `test-group` inside the `tests` directory
2. copy some test file into the new `test-group` directory, e.g. `sequential-track-playback__t1.html`: `dpctf-deploy/tests/test-group/sequential-track-playback__t1.html`
3. run `docker-compose up`
4. when configuring a new test session I can see `test-group` containing one test:
![image](https://github.com/cta-wave/dpctf-deploy/assets/9076000/c50d7047-4051-43d1-b2d7-09f90afa0b84)

**Comment by yanj-github** [comment]
Thank you very much, @FritzHeiden I have got it working now. 
The reason it was not working before is that I have got same folder name for new tests that added to the tests directory.
Changed ./cfhd_15_30_60-local to ./cfhd_15_30_60-local-new worked now.

**Comment by yanj-github** [comment]
This is working, test group folder name added to tests folder shall not be same as existing test.
Close this issue.
