### ISSUE TITLE
docker build process appears to reference Fraunhofer Fokus github repositories

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#7]
I saw this while building the docker image;

![image](https://user-images.githubusercontent.com/8490792/115020399-d5065600-9eba-11eb-98d7-b8fb61fd4a64.png)

I may be misunderstanding the message but I would not have expected references to Fraunhofer Fokus github repositories

**Comment by louaybassbouss** [comment]
@jpiesing this is the component that creates HTML reports from JSON it is an extension of https://github.com/w3c/wptreport. We can move it to a cta-wave github e.g. to https://github.com/cta-wave/wptreport.

**Comment by jpiesing** [comment]
> @jpiesing this is the component that creates HTML reports from JSON it is an extension of https://github.com/w3c/wptreport. We can move it to a cta-wave github e.g. to https://github.com/cta-wave/wptreport.

IMHO there should not be any dependency on Fraunhofer FOKUS infrastructure.

**Comment by louaybassbouss** [comment]
> > @jpiesing this is the component that creates HTML reports from JSON it is an extension of https://github.com/w3c/wptreport. We can move it to a cta-wave github e.g. to https://github.com/cta-wave/wptreport.
> 
> IMHO there should not be any dependency on Fraunhofer FOKUS infrastructure.

agree can you organize a the repo https://github.com/cta-wave/wptreport and give us access. We will transfer the repo and update the dependency.

**Comment by jpiesing** [comment]
> agree can you organize a the repo https://github.com/cta-wave/wptreport and give us access. We will transfer the repo and update the dependency.

@mbergman42 Can you take care of this?

**Comment by cta-source** [comment]
Will do.  We're now ensuring a license in all new repos.  I believe this should be 3-clause BSD?  Or is this situation different?

**Comment by louaybassbouss** [comment]
> Will do. We're now ensuring a license in all new repos. I believe this should be 3-clause BSD? Or is this situation different?

@cta-source  [wptreport](https://github.com/w3c/wptreport) is [MIT](https://github.com/w3c/wptreport/blob/master/LICENSE).

**Comment by cta-source** [comment]
Done.  Let me know if the access is correct; but note that I issued you a member invitation since you didn't seem to be in the organization.

**Comment by louaybassbouss** [comment]
Thanks @cta-source it works 👍

**Comment by mbergman42** [comment]
Great, please let me know when the transfer is complete and linked and we can close the issue.  Thanks--

Mike Bergman
Consumer Technology Association, producer of CES®
d: +1(703) 907-4366
m: +1(609) 865-4402

**Comment by louaybassbouss** [comment]
@mbergman42  @cta-source the content of the Repo is now transferred  from [/fraunhoferfokus/wptreport](https://github.com/fraunhoferfokus/wptreport) into [/cta-wave/wptreport](https://github.com/cta-wave/wptreport). 
@FritzHeiden  can you please update the dependencies in all projects and only use the new repo [/cta-wave/wptreport](https://github.com/cta-wave/wptreport)

**Comment by FritzHeiden** [comment]
@louaybassbouss @mbergman42 I updated wptreport dependencies with the new repository.

**Comment by louaybassbouss** [comment]
thanks @FritzHeiden.  @jpiesing feel free to close this issue.

**Comment by mbergman42** [comment]
Excellent, thank you.

________________________________

**Comment by jpiesing** [comment]
I may have made a trival git error but this fails for me.

./build.sh master latest
.....
 ---> 172ad3770960
Step 14/21 : RUN npm install --global https://github.com/cta-wave/wptreport.git
 ---> Running in 65fa565a2fc9
npm ERR! git rev-list -n1 master: fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! git rev-list -n1 master: Use '--' to separate paths from revisions, like this:
npm ERR! git rev-list -n1 master: 'git <command> [<revision>...] -- [<file>...]'
npm ERR! git rev-list -n1 master: 
npm ERR! Linux 5.4.0-72-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--global" "https://github.com/cta-wave/wptreport.git"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code 128

npm ERR! Command failed: git rev-list -n1 master
npm ERR! fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
npm ERR! Use '--' to separate paths from revisions, like this:
npm ERR! 'git <command> [<revision>...] -- [<file>...]'
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/DPCTF/npm-debug.log
The command '/bin/sh -c npm install --global https://github.com/cta-wave/wptreport.git' returned a non-zero code: 1

**Comment by FritzHeiden** [comment]
I updated the Dockerfile. Please try again and see if the error still occurs

**Comment by jpiesing** [comment]
> I updated the Dockerfile. Please try again and see if the error still occurs

OK now.

Closing.
