### ISSUE TITLE
lack of documentation for how to run the tests on a TV with docker on a PC

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#8]
This may just be a documentation issue but ....

The documentation describes a situation where the tests run on the device where the docker image is deployed and the other device is used to controlled / monitored the test execution.

To run the tests on a TV or phone, I would expect something different.
- a URL that I need to enter on the TV or phone that refers to the docker image on a PC
- controlling / monitoring of the session happens on the PC

Am I missing something?

**Comment by louaybassbouss** [comment]
@jpiesing did you checked the links in the [Running Tests](https://github.com/cta-wave/dpctf-deploy#running-tests) section?  
maybe we need to add only examples for TV URLs pointing to the IP address on the Test Runner but not sure to put else in this section.

**Comment by jpiesing** [comment]
> @jpiesing did you checked the links in the [Running Tests](https://github.com/cta-wave/dpctf-deploy#running-tests) section?
> maybe we need to add only examples for TV URLs pointing to the IP address on the Test Runner but not sure what else to put in this section.

Yes. Those seemed to cover 2 cases.
1) docker installed on PC, running tests on PC, control & manage session on PC
2) docker installed on PC, running tests on PC, control & manage session on other device

They don't appear to cover
3) docker installed on PC, running tests on other device, control & manage session on PC

**Comment by louaybassbouss** [comment]
> They don't appear to cover
> 3) docker installed on PC, running tests on other device, control & manage session on PC

It is documented in section [Managing test sessions](https://github.com/cta-wave/dpctf-test-runner/blob/master/tools/wave/docs/usage/usage.md#4-managing-test-sessions) of the Usage documentation. In summary, you can open the overview page (/_wave/overview.html) and enter the first 8 characters of the session token displayed on the TV to find and manage the session.

**Comment by jpiesing** [comment]
Installing docker on Windows seems to need administrator rights too & running it may need them.

https://stackoverflow.com/questions/58663920/can-i-run-docker-desktop-on-windows-without-admin-privileges

**Comment by jpiesing** [comment]
What I would like to see are headings "Usage on Smart TV" and "Usage on Mobile" where each heading covers the following;
1) Creating a session on a PC
2) Configuring the session on a PC (e.g. defining which tests are part of that session )
3) Launching the session on the Smart TV or mobile phone
4) Reviewing the results on a PC
It's fine if each of these is one sentence and a link to other documentation.

**Comment by louaybassbouss** [comment]
> What I would like to see are headings "Usage on Smart TV" and "Usage on Mobile" where each heading covers the following;
> 
> 1. Creating a session on a PC
> 2. Configuring the session on a PC (e.g. defining which tests are part of that session )
> 3. Launching the session on the Smart TV or mobile phone
> 4. Reviewing the results on a PC
> 
> It's fine if each of these is one sentence and a link to other documentation.

Thanks @jpiesing fully agree we will update the documentation during the day.

**Comment by jpiesing** [comment]
Mostly OK, a few minor editorials, in the section on "Run on separate DUT using companion device",

Open the URL http://<host_ip>:<port>/_wave/configuration.html and enter the session token displayed on the landing page
Access configuration page to configure and start session using one of these options: 

should be

Open the URL http://<host_ip>:<port>/_wave/configuration.html and enter the session token displayed on the landing page **on the DUT**
Access **the** configuration page **on the companion device** to configure and start session using one of these options:

**Comment by jpiesing** [comment]
Another comment :(

It says "On the host machine open the URL http://<host_ip>:<port>/_wave/configuration.html and enter the session token displayed on the landing page (on TV or mobile) to configure and start the session."

Where on the landing page on the PC do I enter the session token from the landing page on the PC or mobile?

I don't see anywhere to enter anything.

![image](https://user-images.githubusercontent.com/8490792/115564702-00bd7d80-a2b9-11eb-8bb3-e4a1042c8941.png)

**Comment by louaybassbouss** [comment]
> Another comment :(
> 
> It says "On the host machine open the URL http://<host_ip>:/_wave/configuration.html and enter the session token displayed on the landing page (on TV or mobile) to configure and start the session."
> 
> Where on the landing page on the PC do I enter the session token from the landing page on the PC or mobile?
> 
> I don't see anywhere to enter anything.

@jpiesing you need to open the `http://<host_ip>:<port>/_wave/configuration.html` and you will see a field where you can enter a token (at least the first 8 characters of the token, for example `64ead080` from your screenshot). As I mentioned in todays Call, you need to rebuild the docker image in order to see this feature (It was added yesterday).

**Comment by jpiesing** [comment]
> @jpiesing you need to open the `http://<host_ip>:<port>/_wave/configuration.html` and you will see a field where you can enter a token (at least the first 8 characters of the token, for example `64ead080` from your screenshot). As I mentioned in todays Call, you need to rebuild the docker image in order to see this feature (It was added yesterday).

I've rebuilt the docker image.
I get a momentary flash a "Resume session" heading with an entry box for the first 8 characters of the token but it then immediately changes to this without giving me any time to enter anything.

![image](https://user-images.githubusercontent.com/8490792/115568083-3d3ea880-a2bc-11eb-8b31-fd07122226c3.png)

This is common to both firefox & chrome.

**Comment by FritzHeiden** [comment]
It seems your test runner is not up to date. With the new feature I removed the text stating a non existing or expired session and replaced it with the input field. I built an image with the recent version and get this screen instead:

![image](https://user-images.githubusercontent.com/9076000/115575019-737f2680-a2c2-11eb-82fc-b5530818728b.png)

When providing a wrong or expired session, there now is this error instead:

![image](https://user-images.githubusercontent.com/9076000/115575202-9f021100-a2c2-11eb-8aeb-07f66ae6b95c.png)

Make sure the image was built with the recent version, increase the revision number for the build script and run the docker-compose command again.

**Comment by jpiesing** [comment]
> Make sure the image was built with the recent version, increase the revision number for the build script and run the docker-compose command again.

I had updated it but I think I'd missed the step of re-running docker-compose.

It now works.

I won't close the issue as the documentation needs to be updated to reflect this.

**Comment by louaybassbouss** [comment]
@jpiesing  docu is updated (last line in the  [Create Image Section](https://github.com/cta-wave/dpctf-deploy#create-image). Feel free to close this issue.

**Comment by jpiesing** [comment]
OK.
