### ISSUE TITLE
improve documentation to refer to test types automatic vs manual

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#9]
The session configuration includes the option for test types being either manual vs automatic.
I'm sort-of aware of these in the context of WPT but what about the context of DPCTF?
Please update the deployment documentation to include a link to where these are defined and why someone running the DPCTF tests might choose one or the other.

![image](https://user-images.githubusercontent.com/8490792/115579870-decaf780-a2c6-11eb-8e2d-ba5ef29566d4.png)

Thanks

**Comment by louaybassbouss** [comment]
@jpiesing for DPCTF we only have automatic tests and no reference browsers. We can hide these 2 options for DPCTF. For now these are only relevant for WMAS. If in future releases we need to add manual tests or to consider tests that pass in desktop browser code bases, we can show these options again. wdyt?

**Comment by jpiesing** [comment]
> @jpiesing for DPCTF we only have automatic tests and no reference browsers. We can hide these 2 options for DPCTF. For now these are only relevant for WMAS. If in future releases we need to add manual tests or to consider tests that pass in desktop browser code bases, we can show these options again. wdyt?

Hiding things that are irrelevant to DPCTF is good. Are you sure all tests are automatic? The file names all include manual.
![image](https://user-images.githubusercontent.com/8490792/115677665-023a8480-a351-11eb-963f-ad2c640aa1d9.png)

**Comment by jpiesing** [comment]
![image](https://user-images.githubusercontent.com/8490792/115677803-25fdca80-a351-11eb-9d01-4aa38c7f7c91.png)

**Comment by louaybassbouss** [comment]
> > @jpiesing for DPCTF we only have automatic tests and no reference browsers. We can hide these 2 options for DPCTF. For now these are only relevant for WMAS. If in future releases we need to add manual tests or to consider tests that pass in desktop browser code bases, we can show these options again. wdyt?
> 
> Hiding things that are irrelevant to DPCTF is good. Are you sure all tests are automatic? The file names all include manual.

@FritzHeiden do we have manual tests?

**Comment by jpiesing** [comment]
> @FritzHeiden do we have manual tests?

I would expect all the tests to be automatic but the file names say otherwise .........

**Comment by louaybassbouss** [comment]
> > @FritzHeiden do we have manual tests?
> 
> I would expect all the tests to be automatic but the file names say otherwise .........

I my view all DPCTF tests are automatic. In the past when we had an interaction with Test Execution Framework, we considered manual tests but now there is no need for it. I will file a new issue in /dpctf-tests project to double check and remove 'manual' from filenames.

**Comment by jpiesing** [comment]
> I my view all DPCTF tests are automatic. In the past when we had an interaction with Test Execution Framework, we considered manual tests but now there is no need for it. I will file a new issue in /dpctf-tests project to double check and remove 'manual' from filenames.

I vaguely remember reading somewhere that the WPT test runner may behave differently based on the presence or absence of "manual" in the filename. With the offline analysis in the observation framework, it might not be quite as simple as renaming the files. Care is needed.

**Comment by louaybassbouss** [comment]
> > I my view all DPCTF tests are automatic. In the past when we had an interaction with Test Execution Framework, we considered manual tests but now there is no need for it. I will file a new issue in /dpctf-tests project to double check and remove 'manual' from filenames.
> 
> I vaguely remember reading somewhere that the WPT test runner may behave differently based on the presence or absence of "manual" in the filename. With the offline analysis in the observation framework, it might not be quite as simple as renaming the files. Care is needed.

Exactly I filed a new issue to check this first. It is all about to set a value for timeout for tests. Usually, in WPT tests, manual means that there is a user interaction (user/tester needs to check something in the page and click on a button) and in this cases the timeout will be disabled by default (because the filename contains manual). In DPCTF, we don't have user interaction (the check/analyses will be done via the OF) but we need to choose a suitable value for timeout to make sure that the video plays until the end.  In my view this is not a manual test because we take care of setting the correct value for timeout in the test.

**Comment by louaybassbouss** [comment]
@jpiesing I had an internal discussion with @FritzHeiden  all tests are automatic (The manual tests were required when we had interaction with the `Test Execution Framework` which we don't have now). We can safely remove `manual` from the file names.

**Comment by FritzHeiden** [comment]
Test file names no longer include -manual annotation. Hiding the controls for selecting manual and automatic still needs to be implemented.

**Comment by louaybassbouss** [comment]
Thanks @FritzHeiden  please make the visibility the manual/automatic buttons configurable and make default visibility value to false.

**Comment by FritzHeiden** [comment]
This is now implemented. Test type configuration UI elements are disabled by default and reference browser selection is disabled if there are none.

**Comment by louaybassbouss** [comment]
@jpiesing feel free to close this issue if you are happy with this solution. If there is a need for manual tests for future releases, we can then change the default value in the configuration.

**Comment by jpiesing** [comment]
Good. There's less risk of people getting confused.
Thank you.
