### ISSUE TITLE
Set up failure

### ISSUE THREAD

**Issue by yanj-github** [cta-wave/dpctf-deploy#91]
Set up test runner failure with the following error in docker log. 

Starting DNS server ...
Dnsmasq version 2.89  Copyright (c) 2000-2022 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile

This software comes with ABSOLUTELY NO WARRANTY.
Dnsmasq is free software, and you are welcome to redistribute it
under the terms of the GNU General Public License, version 2 or 3.
Starting test server ...
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3772c6f5e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ua-parser/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3772c6f910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ua-parser/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3772c6fbb0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ua-parser/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3772c6fd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ua-parser/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7f3772c6fee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/ua-parser/
ERROR: Could not find a version that satisfies the requirement ua-parser (from versions: none)
ERROR: No matching distribution found for ua-parser
CRITICAL:tools.wpt.utils:('/home/ubuntu/DPCTF/_venv3/bin/pip', 'install', '--prefer-binary', 'ua-parser') exited with return code 1
CRITICAL:tools.wpt.utils:b''
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 150, in main
    venv = setup_virtualenv(main_args.venv, main_args.skip_venv_setup, props)
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 128, in setup_virtualenv
    venv.install(name)
  File "/home/ubuntu/DPCTF/tools/wpt/virtualenv.py", line 113, in install
    call(self.pip_path, "install", "--prefer-binary", *requirements)
  File "/home/ubuntu/DPCTF/tools/wpt/utils.py", line 49, in call
    return subprocess.check_output(args).decode('utf8')
  File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('/home/ubuntu/DPCTF/_venv3/bin/pip', 'install', '--prefer-binary', 'ua-parser')' returned non-zero exit status 1.
ln: failed to create symbolic link './*': File exists

**Comment by yanj-github** [comment]
@FritzHeiden it was set up on a new PC, there was no test runner installed before.

**Comment by yanj-github** [comment]
No still has same issue. when I re-build the container completely. Can you help have a look please?

**Comment by jpiesing** [comment]
@FritzHeiden Is it possible to script virtualbox or similar so a new VM is created and the test runner installed once every 24 hours?

**Comment by FritzHeiden** [comment]
This is hard for me to debug remotely. The wpt runner is unable to resolve domain names it requires to install python dependencies. 

What OS are you using?

**Comment by FritzHeiden** [comment]
> @FritzHeiden Is it possible to script virtualbox or similar so a new VM is created and the test runner installed once every 24 hours?

I built the test runner and deployed it on our internal infrastructure multiple times today without issues. IMHO a better solution would be to prebuild test runner images and host them in a public registry somewhere. This way I can periodically build new versions and test the images.

**Comment by yanj-github** [comment]
I am using ubuntu 18. It was working before. The latest changes might linked with it host_override. Do I need to set it. "host_override": "" currently it is an empty string as it on the github.

**Comment by FritzHeiden** [comment]
> I am using ubuntu 18. It was working before. The latest changes might linked with it host_override. Do I need to set it. "host_override": "" currently it is an empty string as it on the github. 

You don't need to set the host_override for the test runner to start up.

So you had a previous version running on this system and with the latest changes this issue occurs?

**Comment by yanj-github** [comment]
> > I am using ubuntu 18. It was working before. The latest changes might linked with it host_override. Do I need to set it. "host_override": "" currently it is an empty string as it on the github.
> 
> You don't need to set the host_override for the test runner to start up.
> 
> So you had a previous version running on this system and with the latest changes this issue occurs?

yep it was working on same OS with old image. I can have a look previous build I have got and will let you know the date of last working version.

**Comment by yanj-github** [comment]
Thanks @FritzHeiden I will try update it to ubuntu 20.
My working set up was build in 2 months ago.

**Comment by yanj-github** [comment]
@FritzHeiden I have got set up working on another PC/VM so this is not a blocker to me.
I have not figured out why one of my VM still has issue but this is low priority now.

**Comment by louaybassbouss** [comment]
@yanj-github feel free to close this issue and reopen or create new one if you face it again. Please use only supported Ubuntu versions

**Comment by yanj-github** [comment]
Wont fix.
