### ISSUE TITLE
release actions

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#94]
1. Rename tests that are "beta" so they appear as "beta" in the test runner (Fraunhofer)​
2. Tag release in github (Fraunhofer+Resillion)​
3. Final check of user documentation for consistency​
4. Complete agreed release documentation based on results of final Fraunhofer sanity check (Bill Rose+Fraunhofer)​

**Comment by FritzHeiden** [comment]
1. While the implementation is done we still need verification for the subsets (released and beta) as well as a page that explains what it means for a test to be released, beta or none, which can be linked in the config page.
2. The test runner is now tagged (https://github.com/cta-wave/dpctf-test-runner/releases/tag/v2.0.0).
Tagging the tests repo depends on solving 1.

**Comment by jpiesing** [comment]
Can we close this? I think so.

**Comment by gitwjr** [comment]
Done. Close.
